### ISSUE TITLE
Guardar información asociada a Stripe

### ISSUE THREAD

**Issue by a8081** [Proyecto-FIS/products#52]
Hay que añadir dos atributos adicionales al objeto product, uno que se llame _**stripe_price**_ y otro _**stripe_produc**t_. Suponiendo que el nuevo producto se llame _**new_product**_ 
```
const stripe = require('stripe')(process.env.STRIPE_PUBLIC_KEY);

// Guardo en product el objeto que devuelve stripe
const product = await stripe.products.create({
            name: new_product.name,
            description: new_product.description
          });
// Guardo en price el objeto que devuelve stripe 
const price = await stripe.prices.create({
            unit_amount: element.format.price,
            currency: 'eur',
            recurring: {interval: 'month'},
            product: new_product.id,
          });
```
Los valores de los atributos serían los siguientes:
```
stripe_price = price.id
stripe_product.id
```
Simplemente meter esto en el create de product para que se almacene la información correspondiente en stripe.

Para utilizar stripe: _npm install stripe_

**Comment by LorenRd** [comment]
@amg98 Recuerda añadir la nueva variable de entorno al readme
