### ISSUE TITLE
Comprobar que el name de format en producto siempre es único

### ISSUE THREAD

**Issue by a8081** [Proyecto-FIS/products#56]
En el [models](https://github.com/Proyecto-FIS/products/blob/main/source/models/Product.js) de products, añadir lo escrito a continuación (**unique: true**) para controlar que los name de los format de los productos siempre sean diferentes.

```
format: [
    {
      name: { type: String, required: [true, "Kind of format required"], unique: true },
      price: {
        type: Number,
        required: [true, "Price required"],
        min: [0, "Minimun price is zero"],
      },
    },
  ],
```

**Comment by LorenRd** [comment]
Esto implica añadir también un validador en el frontend

**Comment by josperdom1** [comment]
Me encargo yo del back y tu del front si te parece.
